apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-health-check-fjwm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/rhtap-demo-evwi-tenant/e2e-nodejs/nodejs-health-check-fjwm@sha256:29a4ff98ed8a13e7e1cb8092a616faa72783e912e42bc8a9dcfafa6bc53726d8
        name: my-nodejs
        resources: {}
status: {}
