apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-fjwm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-fjwm
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-fjwm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-fjwm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-fjwm
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/rhtap-demo-evwi-tenant/e2e-nodejs/nodejs-health-check-fjwm@sha256:29a4ff98ed8a13e7e1cb8092a616faa72783e912e42bc8a9dcfafa6bc53726d8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
